config/routes.rb
PowifyDev::Application.routes.draw do
  get 'proxy' => 'proxy#result', :as => :proxy

  get ':app/delete' => 'proxy#delete', :as => :delete_app

  get ':action' => 'home'
  root :to => "home#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'socket'

	def home
		ip= private_ip.ip_address unless private_ip.nil?
		@host = ip
	end

	def private_ip
		Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
	end

end

app/controllers/proxy_controller.rb
# This class only exists because of the same-domain origin policies
# and Chrome's refusal to set headers in HTML5 docs
class ProxyController < ApplicationController
  require 'net/http'
  require 'uri'

  def result
    render :json => {
      :status => JSON.parse(make_request('http://localhost/status.json')),
      :config => JSON.parse(make_request('http://localhost/config.json')),
      :apps => JSON.parse(apps)
    }
  end

  def apps
    @pow_path = "#{File.expand_path('~/.pow')}"
    pow_apps = {}
    Dir.foreach(@pow_path) do |pow_app|
      unless %w(. .. powify .DS_Store).include?(pow_app)
        pow_apps[pow_app] = {
          :powconfig => powconfig(pow_app),
          :powenv => powenv(pow_app),
          :powrc => powrc(pow_app),
          :rvmrc => rvmrc(pow_app),
          :rbenv => rbenv_version(pow_app)
        }.reject{|k,v| v.nil?}

        pow_apps[pow_app] = nil if pow_apps[pow_app].empty?
      end
    end

    pow_apps.to_json
  end

  # for deleting pow apps
  def delete
    @exists = apps.include?(params[:app])
    @app = params[:app] unless @exists == false

    if @exists
      `rm #{File.expand_path("~/.pow/#{@app}")}`
      redirect_to root_path, :notice => "Pow app deleted"
    else
      render :text => "Given app is not a Pow app"
    end
  end

  private
  def make_request(url)
    url = URI.parse(url)

    request = Net::HTTP::Get.new(url.path)
    request.add_field('host', 'pow')

    Net::HTTP.start(url.host, url.port) {|http|
      http.request(request)
    }.body
  end

  def powconfig(pow_app)
    powconfig_path = "#{@pow_path}/#{pow_app}/.powconfig"
    powconfig = File.open(powconfig_path).readlines if File.exists?(powconfig_path)

    hash = {}
    powconfig.each do |line|
      hash[$1.strip.to_sym] = $2.strip if line =~ /\s?export\s?(.+)=(.+)/i
    end unless powconfig.nil?

    return hash.empty? ? nil : hash
  end

  # return a Hash of all key => value pairs defined in .powenv
  def powenv(pow_app)
    powenv_path = "#{@pow_path}/#{pow_app}/.powenv"
    powenv = File.open(powenv_path).readlines if File.exists?(powenv_path)

    hash = {}
    powenv.each do |line|
      hash[$1.strip.to_sym] = $2.strip if line =~ /\s?export\s?(.+)=(.+)/i
    end unless powenv.nil?

    return hash.empty? ? nil : hash
  end

  def rbenv_version(pow_app)
    rbenv_path = "#{@pow_path}/#{pow_app}/.rbenv-version"
    rbenv_version = File.open(rbenv_path).readlines.join("\n") if File.exists?(rbenv_path)

    hash = {}
    hash[:ruby] = rbenv_version if rbenv_version

    return hash.empty? ? nil : hash
  end

  def rvmrc(pow_app)
    rvmrc_path = "#{@pow_path}/#{pow_app}/.rvmrc"
    rvmrc = File.open(rvmrc_path).readlines.join("\n") if File.exists?(rvmrc_path)

    hash = {}
    if rvmrc =~ /environment_id="(.+)"/i
      hash[:ruby] = $1
    elsif rvmrc =~ /rvm\ ?(.+)/i
      hash[:ruby] = $1
    end

    return hash.empty? ? nil : hash
  end

  def powrc(pow_app)
    powrc_path = "#{@pow_path}/#{pow_app}/.powrc"
    powrc = File.open(powrc_path).readlines if File.exists?(powrc_path)

    hash = {}
    powrc.each do |line|
      hash[$1.strip.to_sym] = $2.strip if line =~ /\s?export\s?(.+)=(.+)/i
    end unless powrc.nil?

    return hash.empty? ? nil : hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.haml
.page
  .wrap
    %h1#status Loading...

  #body

    - flash.each do |key, value|
      #status
        %pre#pre-status.breakout
          %h2= raw value

  #apps.wrap

  .wrap{:style => 'margin-top: 20px'}
    %ul
      %li= link_to 'Powify.dev on github', 'https://github.com/sethvargo/powify.dev'

:javascript
  $(function() {
    $.ajax({
      url : '#{proxy_url(:format => :json)}',
      type : 'GET',
      success : function(data, status, xhr) {
        changeIcon('ok');
        setTitle('Pow is running');
        addStatus(data.status);
        addConfig(data.config);
        addApps(data.apps);
      },
      error : function(data, status, xhr) {
        changeIcon('err');
        setTitle('Pow is not running');
      }
    });
  });

  function changeIcon(newIcon) {
    $('#status').addClass(newIcon);
  }

  function setTitle(newTitle) {
    $('#status').html(newTitle);
  }

  function addStatus(statusJSON) {
    var $status = $('<div id="status" class="none"></div>');
    var $preStatus = $('<pre id="pre-status" class="breakout"></pre>');
      $preStatus.html('<h2>Server Status</h2>');

    $.each(statusJSON, function(key, value) {
      $preStatus.append('<strong>'+key+'</strong>: '+value);
      $preStatus.append('\n');
    });

    $status.append($preStatus);
    $('#body').append($status);
    $status.slideDown('slow');
  }

  function addConfig(configJSON) {
    var $config = $('<div id="config" class="none"></div>');
    var $preConfig = $('<pre id="pre-config" class="breakout"></pre>');
      $preConfig.html('<h2>Server Config</h2>');

    $.each(configJSON, function(key, value) {
      $preConfig.append('<strong>'+key+'</strong>: '+value);
      $preConfig.append('\n');
    });

    $config.append($preConfig);
    $('#body').append($config);
    $config.slideDown('slow');
  }

  function addApps(appsJSON) {
    var $apps = $('<div id="apps" class="none"></div>');
    var $preApps = $('<pre id="pre-apps" class="breakout"></pre>');
      $preApps.html('<h2>My Apps</h2>');

    $.each(appsJSON, function(app, data) {
      buildApp(app, data, $preApps);
    });

    $apps.append($preApps);
    $('#body').append($apps);
    $apps.slideDown('slow');
  }

  function buildApp(app, data, target) {
    var $app = $('<a href="#">'+app+'</a><br />');
    var $infoDiv = $('<div class="none" style="padding:0 0 20px 20px;"></div>');

    if(data == null || typeof(data) == "undefined") {
      $infoDiv.append('No data');
    } else {
      $.each(data, function(key, value) {
        recurseData($infoDiv, key, value, 1);
      });
    }

    $infoDiv.append('<br />');
    $infoDiv.append('<a href="http://'+app+'.dev/" target="_blank">Open '+app+'</a>');
    $infoDiv.append('<br />');
    $infoDiv.append('<a href="http://'+app+'.#{@host}.xip.io/" target="_blank">Open xip.io url</a>');
    $infoDiv.append('<br />');
    $infoDiv.append('<a href="http://powify.dev/'+app+'/delete">Delete '+app+'</a>');


    $app.click(function() {
      $infoDiv.slideToggle('fast');
      return false;
    });

    target.append($app);
    target.append($infoDiv);
  }

  function recurseData(infoDiv, key, value, depth) {
    if(typeof(value) == "object") {
      infoDiv.append('<strong style="font-style:italic;">'+key+'</strong>: ');
      infoDiv.append('<br />');
      $.each(value, function(k, v) {
        recurseData(infoDiv, k, v, depth+1);
      });
    } else {
      infoDiv.append('<strong style="padding-left:'+(10*depth)+'px">'+key+'</strong>: ');
      infoDiv.append(value);
      infoDiv.append('<br />');
    }
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Powify Web
    = stylesheet_link_tag %w(screen)
    = javascript_include_tag %w(jquery jquery-ujs  application)
    = csrf_meta_tag

  %body
    = yield